version: '3'
services:
  jira:
    image: cptactionhank/atlassian-jira-software:7.8.1
    ports:
      - "8081:8080"
    restart: always
  postgres:
    image: postgres:9.4.17-alpine
    restart: always
    environment:
      POSTGRES_PASSWORD: password
    # # restart_policy seems to only work on swarm?
    # restart_policy:
    #   condition: on-failure
  adminer:
    image: adminer
    restart: always
    ports:
      - 8082:8080
